return describe("My tests", function()
  it("should My tests should pass", function()
    return assert.truthy("test")
  end)
  it("should be false #false", function()
    return assert.falsy(nil)
  end)
  it("should be the same", function()
    return assert.same(0, 0)
  end)
  it("Should not be the same", function()
    return assert.are_not_equal(1, 0)
  end)
  return it("Should is_true #true", function()
    return assert.is_true(1 == 1)
  end)
end)
